### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by craqpter** [ChibaniMohamed/Polaris#2]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\\gui.py", line 932, in process
    self.start_error = process.start(path[0])
  File "C:\\process.py", line 135, in start
    draw_delaunay( img_copy, subdiv, (255,219,0) ); #255, 219, 0
  File "C:\\process.py", line 108, in draw_delaunay
    cv2.line(img, pt1, pt2, delaunay_color, lfont, cv2.LINE_AA, 0)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

**Comment by craqpter** [comment]
solution

**Comment by craqpter** [comment]
for t in triangleList:

                pt1 = (int(t[0]), int(t[1]))
                pt2 = (int(t[2]), int(t[3]))
                pt3 = (int(t[4]), int(t[5]))
